services:
  web:
    build: .
    working_dir: /data
    command: python __init__.py
    links:
      - db
    volumes:
      - .:/data
    ports:
      - "8888:8888"
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: impactados
    ports:
      - "3306:3306"